### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by bradcypert** [lamnhan066/features_tour#3]
I had been putting off building a tour for my app (https://www.lunajournal.app) and this library made is _SO_ easy that I was done in about 20 minutes. Thank you so much for building this and sharing it with the world. I appreciate you!

PS. I know this isn't an issue, feel free to close, just wasnt sure how to best reach out to you!

**Comment by lamnhan066** [comment]
I am very glad to hear that. Thank you!
